name: My first workflow

on: push

jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4

          
        - name: Welcome message
          run: |  
            echo "my first github action"
            ls -ltra
            cat README.md 

        - name: Welcome message
          run: cowsay -f dragon " Im DRAGON" >> dragon.txt
             
