name: generate ascci

on: push

jobs:
    ascii_jobs:
        runs-on: ubuntu-latest
        steps:
        - name: checkout Repo
          uses: actions/checkout@v4

        - name: excute shell script
          run: ./asci-script.sh
 
             
